export function throwError() {
  console.trace("yay")
}
